@startgantt

<style>
ganttDiagram {
  closed {
    FontColor red
    BackgroundColor grey
  }
}
</style>

Project starts the 25th of September 2023
-- Initiation --
[Initial PID draft] requires 1 week and starts on the 25th of September 2023 and is colored in Blue
[Act on PID feedback - back and forth with supervisor] requires 1 week and starts on 2nd of October 2023 and is colored in Blue
[Create ethics form] requires 1 day and starts on the 5th of October 2023 and is colored in Blue
[Apply for ethics] requires 1 day and starts on 6th of October 2023 and is colored in Blue
[Submit PID (pending ethics)] requires 1 week and starts on 9th of October 2023 and is colored in Blue

-- Literature review --
[Conduct research on DNS takeovers] requires 1 week and starts on 16th of October 2023 and is colored in Green
[Conduct research on DNS best practices] requires 2 weeks and starts on 9th of October 2023 and is colored in Green
[Conduct research on infra-as-code best practices] requires 2 weeks and starts on 9th of October 2023 and is colored in Green
[Initial Literature Review Draft] requires 2 weeks and starts on 23rd of October 2023 and is colored in Green
[Literature Review Feedback] requires 2 week and starts on 6th of November 2023 and is colored in Green
[Submit Literature Review] requires 1 week and starts on 13th of November 2023 and is colored in Green


-- Methodology --
[Write Methodology Section] requires 2 weeks and starts on 20th of November 2023 and is colored in Purple
[Finalise Methodology Section] requires 1 week and starts on 27th of November 2023 and is colored in Purple

-- Requirements Gathering --
[Create requirements] requires 1 week and starts on 4th of December 2023 and is colored in Pink
[Interview/survey stakeholders] requires 4 days and starts on 5th of December 2023 and is colored in Pink
[Review requirements] requires 3 days and starts on 8th of December 2023 and is colored in Pink

2023-12-11 to 2024-01-08 is closed

-- Design --
[Design architecture for infra-as-code] requires 1 week and starts on 8th of January 2024 and is colored in Orange
[Design architecture for subdomain takeover testing] requires 1 week and starts on 15th of January 2024 and is colored in Orange
[Review architecture] requires 2 days and starts on 18th of January 2024 and is colored in Orange

-- Create --
[Iteration 1] requires 1 week and starts on 22nd of January 2024 and is colored in Cyan
[Iteration 2] requires 1 week and starts on 29th of January 2024 and is colored in Cyan
[Iteration 3] requires 1 week and starts on 5th of February 2024 and is colored in Cyan
[Iteration 4] requires 1 week and starts on 12th of February 2024 and is colored in Cyan
[Iteration 5] requires 1 week and starts on 19th of February 2024 and is colored in Cyan
[Iteration 6] requires 1 week and starts on 26th of February 2024 and is colored in Cyan
[Iteration 7] requires 1 week and starts on 4th of March 2024 and is colored in Cyan
[Iteration 8] requires 1 week and starts on 11th of March 2024 and is colored in Cyan

-- Presentations and report --
[Give first presentation to moderator] requires 2 weeks and starts on 15th of January 2024 and is colored in Khaki
[Write report] requires 25 weeks and ends on 3rd of May 2024 and is colored in Khaki
[Give final presentation] requires 2 weeks and starts on 4th of May 2024 and is colored in Khaki

@endgantt